theme: jekyll-theme-cayman
title: Andrea Marchesini's guides
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - OCI-C_to_OCI_Migration_training_runbook.md
  - OCI-C_to_OCI_Migration.md
  - autoscale_full_lab.md